### ISSUE TITLE
Support to OpenWrt 14.07

### ISSUE THREAD

**Issue by julianofischer** [ibrdtn/ibrdtn#152]
Hi, could you please provide a binary for OpenWrt 14.07 (Barrier Breaker)?

Thanks.

**Comment by julianofischer** [comment]
Well, I compiled ibr-dtn for openwrt trunk (revision 44625) but I have not tested.
I think there is no problem and I will proceed with the tests tomorrow.
If it is general interest, I could make the packages available for download.
I want to build for 14.07 too.

Thanks.

**Comment by morgenroth** [comment]
Binary packages for Barrier Breaker are available for x86:
http://jenkins.ibr.cs.tu-bs.de/download/openwrt/repository/barrier_breaker/x86/packages/ibrdtn/

... and ar71xxx:
http://jenkins.ibr.cs.tu-bs.de/download/openwrt/repository/barrier_breaker/ar71xx/packages/ibrdtn/
