### ISSUE TITLE
configure.ac:49: error: possibly undefined macro: AC_SUBST

### ISSUE THREAD

**Issue by auzias** [ibrdtn/ibrdtn#180]
Hi everyone!

Wanting to work on the bleeding edge I went accross an error just after a `git clone https://github.com/ibrdtn/ibrdtn.git && cd ibrdtn/ibrcommon/ && ./autogen.sh`

## Error
````
## enter directory ibrcommon ##
## run autogen.sh script ##
set version to 1.0.1
configure.ac:49: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:72: error: possibly undefined macro: AC_DEFINE
configure.ac:77: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:97: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:200: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
````

## Solution
Installing the package `pkg-config` solved this issue.
[Thanks mutsu](https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error/9024469#9024469)

**Comment by morgenroth** [comment]
The packages required to build the project are listed in the [README](/ibrdtn/ibrdtn/blob/master/ibrdtn/README) file within the ibrdtn directory.
