### ISSUE TITLE
Windows installer link has no file

### ISSUE THREAD

**Issue by CaptDaags** [ibrdtn/ibrdtn#210]
When clicking on the link for the windows installer at https://github.com/ibrdtn/ibrdtn/wiki/Install-IBR-DTN#windows it throws a HTTP error 404:
Problem accessing /jenkins/job/ibrdtn-win32-release/lastSuccessfulBuild/artifact/ibrdtn-win32/ibrdtn-installer-1.0.0.exe. Reason: Not Found

**Comment by dschuermann** [comment]
Thanks. I fixed the link: https://jenkins.ibr.cs.tu-bs.de/jenkins/job/ibrdtn-win32-release/

**Comment by CaptDaags** [comment]
Thanks for the super quick response Dominik.
Cheers Darrin
