### ISSUE TITLE
Release.key can't be accessed via https

### ISSUE THREAD

**Issue by Don42** [ibrdtn/ibrdtn#212]
http://download.opensuse.org/repositories/home:/j_morgenroth/

This server does not support TLS which makes it impossible to properly validate the _Release.key_ and therefor to validate the packages to be installed.

Possible solutions are:
- Add HTTPS support on this server
- Host the _Release.key_ on another server that supports HTTPS

**Comment by morgenroth** [comment]
The server supports https (now?).
https://download.opensuse.org/repositories/home:/j_morgenroth/
