### ISSUE TITLE
FragmentManager merges bundles successfully but never delivers them to local consumer

### ISSUE THREAD

**Issue by halwaxt** [ibrdtn/ibrdtn#218]
Hi,

I think I found an issue with the FragmentManager. In my lab I do only have two nodes (SENDER and RECEIVER). SENDER transmits a file using `dtnsend` that has a size of 1024 bytes. The deamon is configured to split bundles bigger than 512 bytes. At the RECEIVER side I'm using `dtnrecv`.

The bundles get fragmented correctly and transmitted successfully. The RECEIVER daemon also merges the fragments into one bundle, but it never gets delivered to the `dtnrecv` client.

When bundles got merged by the FragementManager they get injected into the BundleCore using `inject()` method with the param `local=true`. These bundles never will be delivered to the local receiver.

After changing to 3rd param of the method call to `							dtn::core::BundleCore::getInstance().inject(dtn::core::BundleCore::local, merged, false);` the bundle fragments get merged correctly and the resulting bundle gets delivered to the (local) receiver.

Since I'm am not an expert regarding your implementation please take a look at this issue.
Thanks in advance

**Comment by morgenroth** [comment]
Thanks for reporting the issue in such detail. I checked the history of commits and see no reason why merged bundles should be handled as 'local'. So if you like to receive all the the fame for this bugfix, you are invited to submit a pull-request for that change. :-)

**Comment by halwaxt** [comment]
Thank for your quick and friendly response. I created a pull request :-)
