### ISSUE TITLE
GPG Expired key

### ISSUE THREAD

**Issue by ahmad-y-hilal** [ibrdtn/ibrdtn#222]
I tried to install IBRDTN depending on the following 
[https://github.com/ibrdtn/ibrdtn/wiki/Install-IBR-DTN#debianubuntu](url)
I followed the steps under **Debian/Ubuntu**
but I experienced this error when I'm trying to do "sudo apt-get update"  
Error:
> W: http://download.opensuse.org/repositories/home:/j_morgenroth/xUbuntu_16.04/./Release.gpg: Signature by key 144E39A7BA9845106A7FBFBA8984BBB839EBCBCA uses weak digest algorithm (SHA1)
> W: GPG error: http://download.opensuse.org/repositories/home:/j_morgenroth/xUbuntu_16.04 ./ Release: The following signatures were invalid: KEYEXPIRED 1500481402
> W: The repository 'http://download.opensuse.org/repositories/home:/j_morgenroth/xUbuntu_16.04 ./ Release' is not signed.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

I found that the package key is expired in 19/7/2017. Could you please generate a new key pairs and update the Release.key, or guide me to different solution to overcome to succeed the installation.

**Comment by morgenroth** [comment]
Key is updated now. Rebuild of the packages is scheduled. Once this is done, you can give it another try.

https://build.opensuse.org/project/monitor/home:j_morgenroth
