### ISSUE TITLE
Coverage stats are out of date

### ISSUE THREAD

**Issue by dklimkin** [ibrdtn/ibrdtn#232]
As per https://coveralls.io/github/ibrdtn/ibrdtn

LAST BUILD ON BRANCH MASTER
COMMITTED 14 AUG 2017 - 11:29

Last build was 517 in Aug.

**Comment by morgenroth** [comment]
Coveralls are generated by Travis-CI => [.travis.yml](https://github.com/ibrdtn/ibrdtn/blob/master/.travis.yml)
I have no idea why it stopped working.

Any volunteer to fix that?

**Comment by dklimkin** [comment]
I started looking at that before logging the issue but it requires repo access. Can only be investigated/fixed by project owners / maintainers.
