### ISSUE TITLE
Windows installer download requires login

### ISSUE THREAD

**Issue by BrotherPhil** [ibrdtn/ibrdtn#259]
Is there a guest login available, or might it be possible to put a download somewhere else?

**Comment by morgenroth** [comment]
Since the CI builder has changed, the Windows version is no longer available. The old link just points to a dead location.

**Comment by BrotherPhil** [comment]
Is is still possible to build for Windows from source?

**Comment by morgenroth** [comment]
No body knows. Give it a try!
