### ISSUE TITLE
Cannod find a shared library

### ISSUE THREAD

**Issue by esmeraldaliaj** [ibrdtn/ibrdtn#261]
I used the guide provided in the wiki to build and install, after making sure that the needed dependencies are installed too.

When testing it by running `dtnd -i eth0` I get

`dtnd: error while loading shared libraries: libibrdtn-1.0.so.1: cannot open shared object file: No such file or directory`

I am testing in Ubuntu 16.04

**Comment by diogosm** [comment]
Hello @esmeraldaliaj 

Try to copy the lib files from your **ibr-dtn folder** to **/usr/lib**:

`sudo cp $IBR-DTN_FOLDER/ibrdtn/ibrdtn/.libs/* /usr/lib`
`sudo cp $IBR-DTN_FOLDER/iibrcommon/ibrcommon/.libs/* /usr/lib`

and try again: `dtnd`.

Tell me if it works.

My best regards,

**Comment by esmeraldaliaj** [comment]
Yes your solution fixes the issue perfectly.
