### ISSUE TITLE
Problem sending commands to IBRDTN. ERROR : TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by MehrdadAsadi** [ibrdtn/ibrdtn#277]
for examples, when I do need to switch the daemon to extended protocol I do send the message by socket in string but it gives me the error..  (python3.5)

        # switch into protocol extended mode
        writetodaemon_s.send("protocol extended\n")

**Comment by bgernert** [comment]
This problem is not related to IBR-DTN.
Please refer to the [Python 3.5 documentation](https://docs.python.org/3/library/socket.html#socket.socket.send) or use a search engine to get more information about this error message.
