### ISSUE TITLE
Let apps retrieve bundles sent to a REGEX destination

### ISSUE THREAD

**Issue by auzias** [ibrdtn/ibrdtn#34]
As describe within [this mail](https://mail.ibr.cs.tu-bs.de/pipermail/ibr-dtn/2014-July/000924.html) on the [mailing list](https://mail.ibr.cs.tu-bs.de/listinfo/ibr-dtn), delivery to *REGEX destination* could be really handy. The daemon should transfer every bundles sent to:
- dtn://node1/app0
- dtn://node1/app0?
- dtn://node1/app0?p=2
- dtn://node1/app0?lang=en&p=4

at the same application registered as **dtn://node1/app0***.
In the current state, the query is, as expected, considered as a part of the URI. Thus to receive bundles sent to [dtn://node1/app0?lang=en] the user needs to add a registration *app0?lang=en* by doing ```$dtnrecv --name "app0?lang=en```

partial Answered from Johannes Morgenroth:
> There is no way to achieve what you requested without changing the code. If you want to add such a feature, you can simply add query extensions to the EID class and change the compare methods according your needs. Another way would be to add "*" capabilities to the registrations class.

**Comment by morgenroth** [comment]
Since 29ccde51bb607272f89cbaf7cc027217b652816e applications can specify a POSIX regex pattern to subscribe to. Bundles addressed to dtn://node1/app0?lang=en would be delivered to dtnrecv instances called like this:
```
$ dtnrecv --name "app0\?\(.*\)"
```

**Comment by auzias** [comment]
Awesome !
Great work !! :+1:
